language: node_js
cache:
  directories:
    - ~/.npm
notifications:
  email:
    recipients:
      - gopalakshintala@gmail.com
    on_success: always
    on_failure: always
node_js:
  - '11.3.0'
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  on:
    branch: source-v2

