language: node_js
node_js: node
cache: yarn
git:
  depth: 3
deploy:
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  target-branch: master
  on:
    branch: source-v2
notifications:
  slack:
    rooms:
      - overfullstack:PD0LA2Ru0fnlvSPVQFXFookN
    on_success: change
    on_failure: always
