language: node_js
node_js: node
cache: yarn
git:
  depth: 3
script:
  - yarn build
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  token: $GITHUB_TOKEN
  local_dir: public
  target_branch: master
  on:
    branch: source-v2
notifications:
  slack:
    rooms:
      - overfullstack:PD0LA2Ru0fnlvSPVQFXFookN
    on_success: change
    on_failure: always
