# Site settings
title: The Hacker Garage
tagline: My Tech Blog - Book
description: My Hacker blog, where I would like to share my learnings and digitize the notes I make, to make them helpful for other developers :)
baseurl: "https://gopalshackergarage.github.io"
date_format: '%B %d, %Y'
email: gopalakshintala@gmail.com
url: "https://gopalshackergarage.github.io"
twitter_username: gopalakshintala
github_username:  gopalshackergarage
disqus_shortname: 'gopalshackergarage'

# Build settings
markdown: kramdown
paginate: 4
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENSE.md